name: Prepare

on:
  workflow_call:
    inputs:
      verify_tag:
        type: boolean
        required: true
    outputs:
      version:
        value: ${{ jobs.prepare.outputs.version }}

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        run: |
          git describe --tags --always HEAD
          echo "version=$(git describe --tags --always HEAD)" >> $GITHUB_OUTPUT

      # Here you can run a test to make sure the tag matches the version in source code.
      - name: Check release tag
        id: verify_tag
        if: inputs.verify_tag
        run: /bin/true
